# Generated by Django 5.2.4 on 2026-01-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityColumnDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier for the column (e.g., 'activityType')", max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display label for the column', max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('default_width', models.PositiveIntegerField(default=120)),
                ('min_width', models.PositiveIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='System columns cannot be deleted')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('options', models.JSONField(blank=True, default=list, help_text="Options for 'select' data type")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Column Definition',
                'verbose_name_plural': 'Column Definitions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityColumnValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('required', 'Required'), ('regex', 'Regular Expression'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('options', 'Must Be One Of'), ('unique', 'Unique In Sheet'), ('date_format', 'Date Format')], max_length=20)),
                ('rule_value', models.CharField(blank=True, help_text='Rule value (e.g., regex pattern, min length number)', max_length=500)),
                ('error_message', models.CharField(help_text='Error message shown when validation fails', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='activities.activitycolumndefinition')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - archived templates keep this True')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='activity_templates/headers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Template',
                'verbose_name_plural': 'Activity Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_snapshot', models.JSONField(default=list, help_text='Frozen copy of template columns at creation time')),
                ('is_active', models.BooleanField(default=True)),
                ('row_count', models.PositiveIntegerField(default=0, help_text='Cached row count for performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheets', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='activities.activitytemplate')),
            ],
            options={
                'verbose_name': 'Activity Sheet',
                'verbose_name_plural': 'Activity Sheets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict, help_text='Row data: {column_key: value}')),
                ('styles', models.JSONField(default=dict, help_text='Cell styles: {column_key: {bold, italic, backgroundColor, textColor}}')),
                ('height', models.PositiveIntegerField(default=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='activities.activitysheet')),
            ],
            options={
                'verbose_name': 'Sheet Row',
                'verbose_name_plural': 'Sheet Rows',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['sheet', 'row_number'], name='activities__sheet_i_e11ba5_idx'), models.Index(fields=['sheet', 'updated_at'], name='activities__sheet_i_23adfd_idx')],
                'unique_together': {('sheet', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Override default column width', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('column_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='activities.activitycolumndefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_columns', to='activities.activitytemplate')),
            ],
            options={
                'verbose_name': 'Template Column',
                'verbose_name_plural': 'Template Columns',
                'ordering': ['order'],
                'unique_together': {('template', 'column_definition')},
            },
        ),
    ]
