# Generated by Django 5.2.4 on 2026-01-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def table_exists(schema_editor, table_name):
    """Check if a table already exists in the database."""
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor == 'oracle':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM user_tables WHERE table_name = UPPER(%s)",
                [table_name]
            )
            return cursor.fetchone()[0] > 0
    else:
        # For SQLite and other databases
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=%s",
                [table_name]
            )
            return cursor.fetchone() is not None


class SafeCreateModel(migrations.CreateModel):
    """
    A CreateModel operation that safely handles existing tables.
    For Oracle, it checks if the table exists before attempting to create it.
    """
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        
        if table_exists(schema_editor, table_name):
            print(f"Table {table_name} already exists, skipping creation")
            return
        
        # Table doesn't exist, create it normally
        super().database_forwards(app_label, schema_editor, from_state, to_state)
    
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # For backwards, check if table exists before trying to delete
        model = from_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        
        if not table_exists(schema_editor, table_name):
            print(f"Table {table_name} doesn't exist, skipping deletion")
            return
        
        super().database_backwards(app_label, schema_editor, from_state, to_state)


def safe_create_indexes(apps, schema_editor):
    """
    Safely create indexes, skipping if they already exist.
    Works for both Oracle and SQLite.
    """
    db_vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model (handles Oracle truncation)
    ActivitySheetRow = apps.get_model('activities', 'ActivitySheetRow')
    table_name = ActivitySheetRow._meta.db_table
    
    if db_vendor == 'oracle':
        # For Oracle, we need to check if indexes exist first
        with schema_editor.connection.cursor() as cursor:
            # Check and create first index
            cursor.execute(
                "SELECT COUNT(*) FROM user_indexes WHERE index_name = UPPER('actsheetrow_sheet_row_idx')"
            )
            if cursor.fetchone()[0] == 0:
                try:
                    cursor.execute(
                        f'CREATE INDEX "ACTSHEETROW_SHEET_ROW_IDX" ON "{table_name.upper()}" ("SHEET_ID", "ROW_NUMBER")'
                    )
                except Exception as e:
                    if 'ORA-01408' not in str(e) and 'ORA-00955' not in str(e) and 'ORA-00942' not in str(e):
                        raise
                    print(f"Index actsheetrow_sheet_row_idx already exists, skipping")
            
            # Check and create second index
            cursor.execute(
                "SELECT COUNT(*) FROM user_indexes WHERE index_name = UPPER('actsheetrow_sheet_upd_idx')"
            )
            if cursor.fetchone()[0] == 0:
                try:
                    cursor.execute(
                        f'CREATE INDEX "ACTSHEETROW_SHEET_UPD_IDX" ON "{table_name.upper()}" ("SHEET_ID", "UPDATED_AT")'
                    )
                except Exception as e:
                    if 'ORA-01408' not in str(e) and 'ORA-00955' not in str(e) and 'ORA-00942' not in str(e):
                        raise
                    print(f"Index actsheetrow_sheet_upd_idx already exists, skipping")
    else:
        # For SQLite, use IF NOT EXISTS syntax
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{table_name}_sheet_row_idx" ON "{table_name}" ("sheet_id", "row_number")'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{table_name}_sheet_upd_idx" ON "{table_name}" ("sheet_id", "updated_at")'
            )


def safe_create_unique_constraint_sheetrow(apps, schema_editor):
    """
    Safely create unique constraint for ActivitySheetRow, skipping if exists.
    Works for both Oracle and SQLite.
    """
    db_vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model (handles Oracle truncation)
    ActivitySheetRow = apps.get_model('activities', 'ActivitySheetRow')
    table_name = ActivitySheetRow._meta.db_table
    
    if db_vendor == 'oracle':
        with schema_editor.connection.cursor() as cursor:
            # Check if unique constraint already exists
            cursor.execute("""
                SELECT COUNT(*) FROM user_constraints 
                WHERE table_name = UPPER(%s)
                AND constraint_type = 'U'
            """, [table_name])
            if cursor.fetchone()[0] == 0:
                try:
                    cursor.execute(
                        f'ALTER TABLE "{table_name.upper()}" ADD CONSTRAINT "ACTSHEETROW_SHEET_ROW_UNQ" UNIQUE ("SHEET_ID", "ROW_NUMBER")'
                    )
                except Exception as e:
                    if 'ORA-02261' not in str(e) and 'ORA-01408' not in str(e) and 'ORA-00942' not in str(e):
                        raise
                    print(f"Unique constraint on ActivitySheetRow already exists or table issue, skipping")
    else:
        # SQLite: unique constraint is created via unique index
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(
                    f'CREATE UNIQUE INDEX IF NOT EXISTS "{table_name}_sheet_id_row_number_uniq" ON "{table_name}" ("sheet_id", "row_number")'
                )
            except Exception:
                pass  # Index already exists


def safe_create_unique_constraint_templatecolumn(apps, schema_editor):
    """
    Safely create unique constraint for ActivityTemplateColumn, skipping if exists.
    Works for both Oracle and SQLite.
    """
    db_vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model (handles Oracle truncation)
    ActivityTemplateColumn = apps.get_model('activities', 'ActivityTemplateColumn')
    table_name = ActivityTemplateColumn._meta.db_table
    
    if db_vendor == 'oracle':
        with schema_editor.connection.cursor() as cursor:
            # Check if unique constraint already exists
            cursor.execute("""
                SELECT COUNT(*) FROM user_constraints 
                WHERE table_name = UPPER(%s)
                AND constraint_type = 'U'
            """, [table_name])
            if cursor.fetchone()[0] == 0:
                try:
                    # Use table_name dynamically
                    cursor.execute(
                        f'ALTER TABLE "{table_name.upper()}" ADD CONSTRAINT "ACTTEMPCOL_TMPL_COLDEF_UNQ" UNIQUE ("TEMPLATE_ID", "COLUMN_DEFINITION_ID")'
                    )
                except Exception as e:
                    if 'ORA-02261' not in str(e) and 'ORA-01408' not in str(e) and 'ORA-00942' not in str(e):
                        raise
                    print(f"Unique constraint on ActivityTemplateColumn already exists or table issue, skipping")
    else:
        # SQLite: unique constraint is created via unique index
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(
                    f'CREATE UNIQUE INDEX IF NOT EXISTS "{table_name}_template_id_column_def_uniq" ON "{table_name}" ("template_id", "column_definition_id")'
                )
            except Exception:
                pass  # Index already exists


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeCreateModel(
            name='ActivityColumnDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier for the column (e.g., 'activityType')", max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display label for the column', max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('default_width', models.PositiveIntegerField(default=120)),
                ('min_width', models.PositiveIntegerField(default=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False, help_text='System columns cannot be deleted')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('options', models.JSONField(blank=True, default=list, help_text="Options for 'select' data type")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Column Definition',
                'verbose_name_plural': 'Column Definitions',
                'ordering': ['order', 'id'],
            },
        ),
        SafeCreateModel(
            name='ActivityColumnValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('required', 'Required'), ('regex', 'Regular Expression'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('options', 'Must Be One Of'), ('unique', 'Unique In Sheet'), ('date_format', 'Date Format')], max_length=20)),
                ('rule_value', models.CharField(blank=True, help_text='Rule value (e.g., regex pattern, min length number)', max_length=500)),
                ('error_message', models.CharField(help_text='Error message shown when validation fails', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='activities.activitycolumndefinition')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'ordering': ['order'],
            },
        ),
        SafeCreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - archived templates keep this True')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='activity_templates/headers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Template',
                'verbose_name_plural': 'Activity Templates',
                'ordering': ['-updated_at'],
            },
        ),
        SafeCreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_snapshot', models.JSONField(default=list, help_text='Frozen copy of template columns at creation time')),
                ('is_active', models.BooleanField(default=True)),
                ('row_count', models.PositiveIntegerField(default=0, help_text='Cached row count for performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheets', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='activities.activitytemplate')),
            ],
            options={
                'verbose_name': 'Activity Sheet',
                'verbose_name_plural': 'Activity Sheets',
                'ordering': ['-updated_at'],
            },
        ),
        SafeCreateModel(
            name='ActivitySheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict, help_text='Row data: {column_key: value}')),
                ('styles', models.JSONField(default=dict, help_text='Cell styles: {column_key: {bold, italic, backgroundColor, textColor}}')),
                ('height', models.PositiveIntegerField(default=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='activities.activitysheet')),
            ],
            options={
                'verbose_name': 'Sheet Row',
                'verbose_name_plural': 'Sheet Rows',
                'ordering': ['row_number'],
            },
        ),
        # Safe creation of indexes for ActivitySheetRow (handles Oracle ORA-01408)
        migrations.RunPython(safe_create_indexes, migrations.RunPython.noop),
        # Safe creation of unique constraint for ActivitySheetRow
        migrations.RunPython(safe_create_unique_constraint_sheetrow, migrations.RunPython.noop),
        SafeCreateModel(
            name='ActivityTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Override default column width', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('column_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='activities.activitycolumndefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_columns', to='activities.activitytemplate')),
            ],
            options={
                'verbose_name': 'Template Column',
                'verbose_name_plural': 'Template Columns',
                'ordering': ['order'],
            },
        ),
        # Safe creation of unique constraint for ActivityTemplateColumn (handles Oracle ORA-01408)
        migrations.RunPython(safe_create_unique_constraint_templatecolumn, migrations.RunPython.noop),
    ]
