# Generated by Django 5.2.4 on 2026-01-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_default_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheet',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description for the sheet'),
        ),
    ]
