# Generated by Django 5.2.4 on 2026-01-19 15:19

from django.db import migrations, models


def safe_remove_index(apps, schema_editor):
    """
    Safely remove index, handling both old and new index names.
    Works for both Oracle and SQLite.
    """
    db_vendor = schema_editor.connection.vendor
    
    # Get the actual table name from the model
    ActivitySheetRow = apps.get_model('activities', 'ActivitySheetRow')
    table_name = ActivitySheetRow._meta.db_table
    
    if db_vendor == 'oracle':
        with schema_editor.connection.cursor() as cursor:
            # Try to drop old-style index name first, then new-style
            for index_name in ['ACTIVITIES__SHEET_I_E11BA5_IDX', 'ACTSHEETROW_SHEET_ROW_IDX']:
                cursor.execute(
                    "SELECT COUNT(*) FROM user_indexes WHERE index_name = %s",
                    [index_name]
                )
                if cursor.fetchone()[0] > 0:
                    try:
                        cursor.execute(f'DROP INDEX "{index_name}"')
                        print(f"Dropped index {index_name}")
                        return
                    except Exception as e:
                        error_str = str(e)
                        # ORA-01418: specified index does not exist
                        # ORA-02429: cannot drop index used for enforcement of unique/primary key
                        if 'ORA-01418' in error_str or 'ORA-02429' in error_str:
                            print(f"Index {index_name} is part of a constraint or doesn't exist, skipping")
                            continue
                        raise
            print("Index already removed or never existed, skipping")
    else:
        # SQLite
        with schema_editor.connection.cursor() as cursor:
            for index_name in ['activities__sheet_i_e11ba5_idx', f'{table_name}_sheet_row_idx']:
                try:
                    cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_add_notes_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysheetrow',
            options={'ordering': ['row_order'], 'verbose_name': 'Sheet Row', 'verbose_name_plural': 'Sheet Rows'},
        ),
        # Use RunPython for safe index removal
        migrations.RunPython(safe_remove_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='activitysheetrow',
            name='row_number',
            field=models.PositiveIntegerField(help_text='DEPRECATED: Use row_order for ordering. Kept for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='activitysheetrow',
            name='row_order',
            field=models.PositiveIntegerField(default=1, help_text='Display order of the row within the sheet (1-indexed). Can change with inserts.'),
        ),
    ]
