# Generated by Django 5.2.4 on 2026-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_add_notes_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysheetrow',
            options={'ordering': ['row_order'], 'verbose_name': 'Sheet Row', 'verbose_name_plural': 'Sheet Rows'},
        ),
        migrations.RemoveIndex(
            model_name='activitysheetrow',
            name='activities__sheet_i_e11ba5_idx',
        ),
        migrations.AlterField(
            model_name='activitysheetrow',
            name='row_number',
            field=models.PositiveIntegerField(help_text='DEPRECATED: Use row_order for ordering. Kept for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='activitysheetrow',
            name='row_order',
            field=models.PositiveIntegerField(default=1, help_text='Display order of the row within the sheet (1-indexed). Can change with inserts.'),
        ),
    ]
