# Generated by Django 5.2.4 on 2026-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activitysheetrow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheetrow',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='If True, this activity has been submitted and cannot be edited.'),
        ),
        migrations.AddField(
            model_name='activitysheetrow',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when activity was submitted', null=True),
        ),
    ]
