# Generated by Django 5.2.4 on 2026-01-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_add_row_submission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycolumndefinition',
            name='allows_attachment',
            field=models.BooleanField(default=False, help_text='Whether this column allows file attachments'),
        ),
        migrations.AddField(
            model_name='activitycolumndefinition',
            name='attachment_required',
            field=models.BooleanField(default=False, help_text='Whether attachment is required when allows_attachment is True'),
        ),
        migrations.CreateModel(
            name='ActivityRowAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_key', models.CharField(help_text='The column key this attachment belongs to', max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_content', models.BinaryField(help_text='Binary file content stored as blob')),
                ('is_image', models.BooleanField(default=False, help_text='True if file is an image that can be previewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activitysheetrow')),
            ],
            options={
                'verbose_name': 'Row Attachment',
                'verbose_name_plural': 'Row Attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['row', 'column_key'], name='activities__row_id_13f607_idx')],
            },
        ),
    ]
