# Generated by Django 5.2.4 on 2026-01-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicklinks', '0002_user_quicklink_preferences'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userquicklinkpreference',
            new_name='quicklinks__user_id_d1e3ad_idx',
            old_name='quicklinks__user_id_b68b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='userquicklinkpreference',
            new_name='quicklinks__user_id_fb1e2f_idx',
            old_name='quicklinks__user_id_731cb1_idx',
        ),
    ]
