# Generated by Django 5.2.4 on 2025-12-15 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_roles(apps, schema_editor):
    """Create default system roles."""
    Role = apps.get_model('authentication', 'Role')
    
    roles = [
        {
            'name': 'super_admin',
            'display_name': 'Super Administrator',
            'description': 'Full system access with all permissions.',
            'is_system_role': True,
        },
        {
            'name': 'admin',
            'display_name': 'Administrator',
            'description': 'Administrative access to manage resources.',
            'is_system_role': True,
        },
        {
            'name': 'user',
            'display_name': 'User',
            'description': 'Regular user with basic access.',
            'is_system_role': True,
        },
    ]
    
    for role_data in roles:
        Role.objects.get_or_create(name=role_data['name'], defaults=role_data)


def migrate_user_roles(apps, schema_editor):
    """Migrate existing users from string role to Role FK."""
    User = apps.get_model('authentication', 'User')
    Role = apps.get_model('authentication', 'Role')
    
    # Get role mapping
    role_map = {role.name: role for role in Role.objects.all()}
    
    # Default role if none exists
    default_role = role_map.get('user')
    
    # Update each user
    for user in User.objects.all():
        # The old role field should still exist at this point
        old_role_name = getattr(user, 'role', None)
        if old_role_name and old_role_name in role_map:
            user.user_role = role_map[old_role_name]
        else:
            user.user_role = default_role
        user.save()


def create_default_page_permissions(apps, schema_editor):
    """Create default page permissions for roles."""
    Role = apps.get_model('authentication', 'Role')
    PagePermission = apps.get_model('authentication', 'PagePermission')
    
    roles = {role.name: role for role in Role.objects.all()}
    
    # Define permissions: (page_name, display_name, description, [role_names])
    permissions = [
        ('news', 'News', 'View news and announcements', ['user', 'admin', 'super_admin']),
        ('surveys', 'Surveys', 'View and participate in surveys', ['user', 'admin', 'super_admin']),
        ('quick-links', 'Quick Links', 'View quick links', ['user', 'admin', 'super_admin']),
        ('manage-surveys', 'Manage Surveys', 'Create, edit, and delete surveys', ['admin', 'super_admin']),
        ('manage-news', 'Manage News', 'Create, edit, and delete news articles', ['admin', 'super_admin']),
        ('manage-quicklinks', 'Manage Quick Links', 'Create, edit, and delete quick links', ['admin', 'super_admin']),
        ('manage-users', 'Manage Users', 'Manage user accounts and roles', ['admin', 'super_admin']),
        ('manage-roles', 'Manage Roles', 'Manage system roles and permissions', ['super_admin']),
        ('system-settings', 'System Settings', 'Configure system settings', ['super_admin']),
    ]
    
    for page_name, display_name, description, role_names in permissions:
        for role_name in role_names:
            role = roles.get(role_name)
            if role:
                PagePermission.objects.get_or_create(
                    name=page_name,
                    role=role,
                    defaults={
                        'display_name': display_name,
                        'description': description,
                    }
                )


def reverse_migrate_roles(apps, schema_editor):
    """Reverse migration - restore role string field from FK."""
    User = apps.get_model('authentication', 'User')
    
    for user in User.objects.all():
        if user.user_role:
            user.role = user.user_role.name
        else:
            user.role = 'user'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_online_user_last_seen'),
    ]

    operations = [
        # Step 1: Create Role model
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique role name (e.g., super_admin, admin, user)', max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable display name for the role', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its permissions')),
                ('is_system_role', models.BooleanField(default=False, help_text='Whether this is a system-defined role that cannot be deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the role was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the role was last updated')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'auth_role',
                'ordering': ['name'],
            },
        ),
        
        # Step 2: Create default roles
        migrations.RunPython(create_default_roles, migrations.RunPython.noop),
        
        # Step 3: Add user_role FK field (nullable initially)
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='role_id', help_text='User role in the system (FK to Role table)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='authentication.role'),
        ),
        
        # Step 4: Migrate existing user roles from string to FK
        migrations.RunPython(migrate_user_roles, reverse_migrate_roles),
        
        # Step 5: Remove old role CharField
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        
        # Step 6: Update auth_type field
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('regular', 'Regular Email/Password'), ('azure', 'Azure AD SSO'), ('ldap', 'LDAP Authentication')], default='regular', help_text='Authentication type used for this user', max_length=20),
        ),
        
        # Step 7: Create PagePermission model
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Page/feature identifier (matches frontend route name)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable display name for the page/feature', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the page/feature')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the permission was created')),
                ('role', models.ForeignKey(help_text='Role that has access to this page', on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='authentication.role')),
            ],
            options={
                'verbose_name': 'Page Permission',
                'verbose_name_plural': 'Page Permissions',
                'db_table': 'auth_page_permission',
                'ordering': ['name', 'role__name'],
                'unique_together': {('name', 'role')},
            },
        ),
        
        # Step 8: Create default page permissions
        migrations.RunPython(create_default_page_permissions, migrations.RunPython.noop),
    ]
