# Generated by Django 5.2.4 on 2025-12-15 12:25

import django.db.models.deletion
from django.db import migrations, models


def populate_role_from_user_role(apps, schema_editor):
    """
    Populate the role column based on user_role FK.
    
    Logic:
    - If user_role.name is super_admin -> role = 'super_admin'
    - If user_role.name is admin -> role = 'admin'
    - If user_role.name is user -> role = 'user'
    - If user_role is a custom role (e.g., News_admin) -> role = 'admin'
    - If user_role is None -> role = 'user'
    """
    User = apps.get_model('authentication', 'User')
    
    for user in User.objects.select_related('user_role').all():
        if user.user_role:
            role_name = user.user_role.name
            if role_name == 'super_admin':
                user.role = 'super_admin'
            elif role_name == 'admin':
                user.role = 'admin'
            elif role_name == 'user':
                user.role = 'user'
            else:
                # Custom role -> grant admin access level
                user.role = 'admin'
        else:
            user.role = 'user'
        user.save(update_fields=['role'])


def reverse_populate(apps, schema_editor):
    """Reverse is a no-op - we keep the data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_role_and_page_permission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator'), ('super_admin', 'Super Administrator')], db_index=True, default='user', help_text='User access level for endpoint validation (super_admin, admin, user)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='user_role_id', help_text='Role for page-level permissions (FK to Role table)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role'),
        ),
        # Populate role column from existing user_role FK
        migrations.RunPython(populate_role_from_user_role, reverse_populate),
    ]
