# Generated by Django 5.2.4 on 2025-12-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(help_text='Cached full name/email for historical tracking', max_length=255)),
                ('action', models.CharField(choices=[('SURVEY_CREATE', 'Survey Created'), ('SURVEY_UPDATE', 'Survey Updated'), ('SURVEY_DELETE', 'Survey Deleted'), ('SURVEY_ACTIVATE', 'Survey Activated'), ('SURVEY_DEACTIVATE', 'Survey Deactivated'), ('SURVEY_SUBMIT', 'Survey Submitted'), ('NEWSLETTER_CREATE', 'Newsletter Created'), ('NEWSLETTER_UPDATE', 'Newsletter Updated'), ('NEWSLETTER_DELETE', 'Newsletter Deleted'), ('ROLE_ASSIGN', 'Role Assigned'), ('ROLE_CHANGE', 'Role Changed'), ('PERMISSION_GRANT', 'Permission Granted'), ('PERMISSION_REVOKE', 'Permission Revoked')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected object (supports UUID and int)', max_length=255)),
                ('object_name', models.CharField(help_text='Cached object name (survey title, newsletter title, user email)', max_length=500)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Key changes: {"field": {"old": "...", "new": "..."}}')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred (UAE timezone)')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Model being affected (e.g., Survey, Newsletter, User)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='audit_actor_time_idx'), models.Index(fields=['action', '-timestamp'], name='audit_action_time_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
