# Generated by Django 5.2.4 on 2026-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SURVEY_CREATE', 'إنشاء استبيان'), ('SURVEY_UPDATE', 'تحديث استبيان'), ('SURVEY_DELETE', 'حذف استبيان'), ('SURVEY_ACTIVATE', 'تفعيل استبيان'), ('SURVEY_DEACTIVATE', 'إلغاء تفعيل استبيان'), ('SURVEY_SUBMIT', 'نشر استبيان'), ('NEWSLETTER_CREATE', 'إنشاء خبر'), ('NEWSLETTER_UPDATE', 'تحديث خبر'), ('NEWSLETTER_DELETE', 'حذف خبر'), ('ROLE_ASSIGN', 'تعيين دور'), ('ROLE_CHANGE', 'تغيير دور'), ('PERMISSION_GRANT', 'منح صلاحية'), ('PERMISSION_REVOKE', 'سحب صلاحية')], db_index=True, help_text='Type of action performed', max_length=50),
        ),
    ]
